//error 
export const GET_ERROR = "GET_ERROR"

// category types
export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY"
export const CREATE_CATEGORY="CREATE_CATEGORY"
export const GET_ONE_CATEGORY ="GET_ONE_CATEGORY"


//brand type
export const GET_ALL_BRAND = "GET_ALL_BRAND"
export const CREATE_BRAND = "CREATE_BRAND"
export const GET_ONE_BRAND = "GET_ONE_BRAND"


//subcategory type
export const CREATE_SUB_CATEGORY= "CREATE_SUB_CATEGORY"
export const GET_SUB_CATEGORY ="GET_SUB_CATEGORY"


// Product Type 
export const CREATE_PRODUCT = "CREATE_PRODUCT"
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT"
export const GET_PRODUCT_DETAILS ="GET_PRODUCT_DETAILS"
export const GET_PRODUCTS_LIKE = "GET_PRODUCTS_LIKE"
export const DELETE_PRODUCT ="DELETE_PRODUCT"
export const UPDATE_PRODUCT ="UPDATE_PRODUCT"

//Auth Type
export const CREATE_NEW_USER = "CREATE_NEW_USER"
export const LOGIN_USER = "LOGIN_USER"
export const FOREGT_PASSWORD = "FOREGT_PASSWORD"
export const VERIFY_PASSWORD = "VERIFY_PASSWORD"
export const RESET_PASSWORD = "RESET_PASSWORD"
export const GET_CURERNT_USER = "GET_CURERNT_USER"
export const UPDATE_USER_PROFILE="UPDATE_USER_PROFILE"
export const UPDATE_USER_PASSWORD ="UPDATE_USER_PASSWORD"

// review Type
export const CREATE_REVIEW ="CREATE_REVIEW"
export const UPDATE_REVIEW = "UPDATE_REVIEW"
export const DELETE_REVIEW ="DELETE_REVIEW"
export const ALL_REVIEW_PRODUCT = "ALL_REVIEW_PRODUCT"

// wish Type
export const ADD_FAV_PRODUCT ="ADD_FAV_PRODUCT"
export const REMOVE_FAV_PRODUCT ="REMOVE_FAV_PRODUCT"
export const USER_WISHLIST = "USER_WISHLIST"


// CouponType
export const CREATE_COUPON = "CREATE_COUPON"
export const GET_ALL_COUPONS ="GET_ALL_COUPONS"
export const DELETE_COUPON ="DELETE_COUPON"
export const GET_ONE_COUPON ="GET_ONE_COUPON"
export const EDIT_COUPON = "EDIT_COUPON"

// user address Types
export const ADD_USER_ADDRESS = "ADD_USER_ADDRESS" 
export const GET_ONE_ADDRESS = "GET_ONE_ADDRESS"
export const DELETE_USER_ADDRESS = "DELETE_USER_ADDRESS"
export const GET_ONE_USER_ADDRESS = "GET_ONE_USER_ADDRESS"
export const EDIT_USER_ADDRESS = "EDIT_USER_ADDRESS"



